---
- hosts: master
  become_user: root
  become: yes
  become_method: sudo
  roles:
    - kubernetes
    - cluster
    - deploy

- hosts: workers
  become_user: root
  become: yes
  become_method: sudo
  roles:
    - kubernetes
    - joinCluster

- hosts: master
  become_user: root
  become: yes
  become_method: sudo
  roles:
    - recognize
 

- hosts: master
  become_user: root
  become: yes
  become_method: sudo
  roles:
    - destroy
  tags: [never,destroy]

- hosts: master,workers
  become_user: root
  become: yes
  become_method: sudo
  roles:
    - destroy_cluster
  tags: [never, destroy_cluster]

- hosts: master
  become_user: root
  become: yes
  become_method: sudo
  roles:
    - destroy
    - deploy
  tags: [never, redeploy]

