- name: Install calico pod network
  become: yes
  command: "{{ item }}"
  with_items:
    - kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
    - kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
