---

- import_tasks: initCluster.yaml
  tags: cluster

- name: install calico CNI
  shell: "kubectl apply -f installCNI.yaml"
  tags: cluster

- name: Install nvidia docker plugin
  shell: "kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta4/nvidia-device-plugin.yml"
  tags: cluster

- import_tasks: copyJoinClusterCommand.yaml
  tags: cluster
